# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/audio-algebra',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/audio-algebra',
                'lib_path': 'audio_algebra'},
  'syms': {'audio_algebra.core': {'audio_algebra.core.foo': ('core.html#foo', 'audio_algebra/core.py')}}}