name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: [run: sudo apt-get update; sudo apt-get install ffmpeg libsndfile-dev, uses: fastai/workflows/nbdev-ci@master]
